const campus={
    campus:{
        sedes:{
            bucaramanga:{
                numero:'1111'
            },
            bogota:{
                numero:'1111'
            },
            medellin:{
                numero:'1111'
            },
            mexico:{
                numero:'1111'
            }
        }
    },
    trainers:[
        {nombre:'miguel',
        telefono:'333333',
        teams:'',
        email:'miguel@miguel.com'
    }],
    campers:[{
        nombre:'Andres',
        telefono:'5555',
        teams:'',
        email:'andres@andres.com',
        nivelActual: '', 
        barrio:'Florida',
        medioTransporte:'Moto',
    }],
    niveles:{
        bajo:{
            preRequisito:'Ninguno',
            tecnologia:'',
            obligatoria:''
        },
        medio:'',
        avanzado:'',
    },
    tecnologias:'',
    teams:'',
    roadMap:'',

}